name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main
      - staging
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }}
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no thunder@62.72.5.193 <<EOF
            source ~/.bashrc
            export CURRENT_BRANCH="$CURRENT_BRANCH"

            # Directory navigation based on the branch
            cd front/demo-ci-cd

            case ${CURRENT_BRANCH} in
              "main")
                cd main
                ;;
              "staging")
                cd staging
                ;;
              "dev")
                cd dev
                ;;
              *)
                echo "Unsupported branch: $CURRENT_BRANCH"
                exit 1
                ;;
            esac

            # Perform Git operations and build for the selected branch
            ls -la
            git checkout $CURRENT_BRANCH
            git pull origin $CURRENT_BRANCH
            npm install
            npm run build

            # Manage the application using pm2 based on branch
            pm2 delete $CURRENT_BRANCH
            pm2 flush
            PORT=$(case ${CURRENT_BRANCH} in
                      "main") echo "3007" ;;
                      "staging") echo "3009" ;;
                      "dev") echo "3008" ;;
                      *) exit 1 ;;
                    esac)
            pm2 start npm --name "$CURRENT_BRANCH" -- start
            pm2 save
          EOF
