name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main", "staging", "dev" ]

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Debug Build Output
        run: ls -al

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.TOKEN }} 
