name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main
      - staging
      - dev

env:
  GITHUB_BRANCH: ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "SSH setup complete."

          echo "Connecting to the VPS..."
          ssh -o StrictHostKeyChecking=no thunder@62.72.5.193 << 'EOF'
            echo "GITHUB_REF value: $GITHUB_REF"

            echo "Determining deployment target based on branch..."

            # Determine which subdomain to deploy based on the branch
            if [ "$GITHUB_REF" == "refs/heads/main" ]; then
              TARGET_DIR="/front/demo-ci-cd/main"
              DOMAIN="main.technithunderlabs.com"
              echo "Deploying to main branch"
            elif [ "$GITHUB_REF" == "refs/heads/staging" ]; then
              TARGET_DIR="/front/demo-ci-cd/staging"
              DOMAIN="staging.technithunderlabs.com"
              echo "Deploying to staging branch"
            elif [ "$GITHUB_REF" == "refs/heads/dev" ]; then
              TARGET_DIR="/front/demo-ci-cd/dev"
              DOMAIN="dev.technithunderlabs.com"
              echo "Deploying to dev branch"
            else
              echo "No valid branch detected. Skipping deployment."
              exit 1
            fi

            echo "Navigating to project directory for $DOMAIN..."
            cd $TARGET_DIR
            cd demo-ci-cd

            echo "Checking out the correct branch: $(basename $GITHUB_REF)"
            git checkout $(basename $GITHUB_REF)
            echo "Pulling the latest code..."
            git pull origin $(basename $GITHUB_REF)

            echo "Installing project dependencies..."
            npm install

            echo "Building the project..."
            npm run build

            echo "Starting the app with pm2..."
            pm2 restart $DOMAIN || pm2 start npm --name "$DOMAIN" -- run dev
            echo "App deployment complete."
          EOF
