name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main
      - staging
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          echo "DEPLOY_STEP: Current directory: $(pwd)"
          npm install

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }} 
        run: |
          echo "DEPLOY_SETUP: Current directory: $(pwd)"
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "SSH_CONNECT: Current directory: $(pwd)"
          ssh -o StrictHostKeyChecking=no thunder@62.72.5.193 <<EOF
            echo "SSH_SESSION: Current directory: $(pwd)"
            cd ~
            export CURRENT_BRANCH="$CURRENT_BRANCH"
            echo "BRANCH_INFO: Current directory: $(pwd)"
            
            if [ ${CURRENT_BRANCH} == "main" ]; then
              TARGET_DIR="/front/demo-ci-cd/main"
              DOMAIN="main.technithunderlabs.com"
            elif [ ${CURRENT_BRANCH} == "staging" ]; then
              TARGET_DIR="/front/demo-ci-cd/staging"
              DOMAIN="staging.technithunderlabs.com"
            elif [ ${CURRENT_BRANCH} == "dev" ]; then
              TARGET_DIR="/front/demo-ci-cd/dev"
              DOMAIN="dev.technithunderlabs.com"
            else
              exit 1
            fi

            echo "TARGET_DIR: Current directory: $(pwd)"
            cd
            cd $TARGET_DIR
            echo "ENTER_DIR: Current directory: $(pwd)"
            cd demo-ci-cd
            echo "ENTER_SUBDIR: Current directory: $(pwd)"

            git checkout $(basename ${CURRENT_BRANCH})
            git pull origin $(basename ${CURRENT_BRANCH})

            echo "INSTALL_DEPS: Current directory: $(pwd)"
            npm install

            echo "BUILD_PROJECT: Current directory: $(pwd)"
            npm run build

            echo "PM2_SETUP: Current directory: $(pwd)"
            pm2 restart $DOMAIN || pm2 start npm --name "$DOMAIN" -- run dev
          EOF
