name: Deploy to GitHub Pages

on:
  push:
    branches: ["main", "staging", "dev"]

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Adjust as per your project requirements

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Debug Build Output
        run: |
          echo "Build Output Contents:"
          ls -al  # List the contents of the build output folder (adjust if your build output is elsewhere)

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./out

  deploy:
  runs-on: ubuntu-latest
  needs: build-and-deploy
  environment:
    name: github-pages # Required environment for Pages deployment
  steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: github-pages # Name of the artifact uploaded
        path: ./out # Path where the artifact will be downloaded

    - name: Debug Artifact Size
      run: |
        echo "Checking artifact size:"
        du -sh ./out  # Check size of the build artifact
        echo "Listing all files in the build artifact:"
        find ./out  # List all files in the build artifact directory

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ secrets.TOKEN }} # Your repository secret
