name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main
      - staging
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # - name: Install Dependencies
      #   run: |
      #     echo "DEPLOY_STEP: Current directory: $(pwd)"
      #     npm install

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }} 
        shell: bash
        run: |
          echo "DEPLOY_SETUP: Current directory: $(pwd)"
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "SSH_CONNECT: Current directory: $(pwd)"
          ssh -o StrictHostKeyChecking=no thunder@62.72.5.193 <<EOF
            echo "SSH_SESSION: Current directory: $(pwd)"
            source ~/.bashrc
            export CURRENT_BRANCH="$CURRENT_BRANCH"
            echo "BRANCH_INFO: Current directory: $(pwd)"

            ls -la
            cd front
            echo "Now In Front Directory ========================>"
            ls -la
            cd demo-ci-cd
            echo "Now In demo-ci-cd Directory ========================>"
            ls -la
            
            if [ ${CURRENT_BRANCH} == "main" ]; then
              cd main
              DOMAIN="main.technithunderlabs.com"
            elif [ ${CURRENT_BRANCH} == "staging" ]; then
              cd staging
              DOMAIN="staging.technithunderlabs.com"
            elif [ ${CURRENT_BRANCH} == "dev" ]; then
              cd dev
              DOMAIN="dev.technithunderlabs.com"
            else
              exit 1
            fi

            echo "TARGET_DIR is set to: $TARGET_DIR"

            cd $TARGET_DIR
            ls -la
            echo "=================> Current Branch ${CURRENT_BRANCH}"
            echo "=================> Currently In ${TARGET_DIR}"
            ls -la

            git checkout $(basename ${CURRENT_BRANCH})
            git pull origin $(basename ${CURRENT_BRANCH})

            echo "INSTALL_DEPS: Current directory: $(pwd)"
            npm install

            echo "BUILD_PROJECT: Current directory: $(pwd)"
            npm run build

            echo "PM2_SETUP: Current directory: $(pwd)"
            pm2 restart $DOMAIN || pm2 start npm --name "$DOMAIN" -- run dev
          EOF
